services:
  dev:
    image: ghcr.io/lesomnus/dev-golang:1.24
    command: sleep infinity

    user: "1000"
    privileged: true
    environment:
      SHELL: /bin/zsh

    volumes:
      - command.history:/commandhistory
      - go.cache.mod:/go/pkg/mod
      - go.cache.bin:/home/hypnos/.cache/go-build

      - ..:/workspace
      - ${HOME}/workspaces:/workspaces
      - ${HOME}/.claude:/home/hypnos/.claude

    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G
        reservations:
          cpus: "2"
          memory: 4G

volumes:
  go.cache.mod:
  go.cache.bin:
  command.history:
